In [1]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [52]:
np.array(my_mat).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
np.arange(0, 5, 1)

array([0, 1, 2, 3, 4])

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [53]:
np.linspace(0, 4, 100).reshape(10,10)

array([[0.        , 0.04040404, 0.08080808, 0.12121212, 0.16161616,
        0.2020202 , 0.24242424, 0.28282828, 0.32323232, 0.36363636],
       [0.4040404 , 0.44444444, 0.48484848, 0.52525253, 0.56565657,
        0.60606061, 0.64646465, 0.68686869, 0.72727273, 0.76767677],
       [0.80808081, 0.84848485, 0.88888889, 0.92929293, 0.96969697,
        1.01010101, 1.05050505, 1.09090909, 1.13131313, 1.17171717],
       [1.21212121, 1.25252525, 1.29292929, 1.33333333, 1.37373737,
        1.41414141, 1.45454545, 1.49494949, 1.53535354, 1.57575758],
       [1.61616162, 1.65656566, 1.6969697 , 1.73737374, 1.77777778,
        1.81818182, 1.85858586, 1.8989899 , 1.93939394, 1.97979798],
       [2.02020202, 2.06060606, 2.1010101 , 2.14141414, 2.18181818,
        2.22222222, 2.26262626, 2.3030303 , 2.34343434, 2.38383838],
       [2.42424242, 2.46464646, 2.50505051, 2.54545455, 2.58585859,
        2.62626263, 2.66666667, 2.70707071, 2.74747475, 2.78787879],
       [2.82828283, 2.86868687, 2.9090909

In [18]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
arr = np.random.randint(2,4, size=(5,4))

In [54]:
arr.reshape(5,2,2).T

array([[[2, 2, 2, 2, 2],
        [3, 2, 3, 3, 3]],

       [[3, 3, 3, 2, 3],
        [2, 3, 2, 2, 2]]])

In [39]:
arr.max()

3

In [40]:
arr.min()

2

In [44]:
arr.argmax()

1

In [50]:
arr.reshape(5,2,2).T

array([[[2, 2, 2, 2, 2],
        [3, 2, 3, 3, 3]],

       [[3, 3, 3, 2, 3],
        [2, 3, 2, 2, 2]]])

In [51]:
arr.dtype

dtype('int64')

In [63]:
slice_arr = arr[2:]

In [64]:
slice_arr

array([[2, 3, 3, 2],
       [2, 2, 3, 2],
       [2, 3, 3, 2]])

In [65]:
arr

array([[2, 3, 3, 2],
       [2, 3, 2, 3],
       [2, 3, 3, 2],
       [2, 2, 3, 2],
       [2, 3, 3, 2]])

In [79]:
arr.shape[:]

(5, 4)

In [81]:
arr[arr > 2]

array([3, 3, 3, 3, 3, 3, 3, 3, 3])

In [82]:
arr.shape

(5, 4)

In [98]:
arr = np.arange(0, 9)

In [99]:
arr **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [100]:
arr +=2

In [101]:
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr-=2

In [103]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [122]:
dot = np.dot(arr.reshape(3,3).T, np.ones((3,3)))

In [123]:
dot

array([[ 9.,  9.,  9.],
       [12., 12., 12.],
       [15., 15., 15.]])

In [124]:
np.sinh(arr)

array([0.00000000e+00, 1.17520119e+00, 3.62686041e+00, 1.00178749e+01,
       2.72899172e+01, 7.42032106e+01, 2.01713157e+02, 5.48316123e+02,
       1.49047883e+03])